### ISSUE TITLE
How to get facebook login working with angular?

### ISSUE THREAD

**Issue by MogauGeeky** [mkloubert/nativescript-social-login#10]
Hi guys

I am using the plugin with angular way but I always get the following message in the facebook login pop up
"You are not logged in: You are not logged in. Please log in and try again."
![image](https://cloud.githubusercontent.com/assets/10864511/23453299/8568ea0c-fe70-11e6-871f-8dde9a35bf3e.png)

I have no idea how to fix this

**Comment by votiakov** [comment]
Hi @MogauGeeky !

Looks like your facebook app is not configured properly or wrong app id is given. 

By the way on which platforms does it happen?

**Comment by dgomezs** [comment]
I did a quick example today on how the plugin works 
https://github.com/dgomezs/facebook-login

as @votiakov  mentioned you need to configure your app on Facebook providing the parameters. I put a screenshot in the repo with the config. 

Let me know if you have any questions

**Comment by MogauGeeky** [comment]
Hi guys

Thanks for the help, much appreciated
@dgomezs thanks for the repo I managed to solve my issue by going through your example.

Sorry for the delayed reply... I didn't have the time to look into this project till now

Cheers!
