### ISSUE TITLE
does not work whith geolocation

### ISSUE THREAD

**Issue by raphaelratuczne** [mkloubert/nativescript-social-login#13]
In my project i work with angular and the social login plugin is not compatible with geolocation. On build a project for android give me an error with the message: "Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzf"
So in app.gradle i substitute the version of play-services-auth from 8.4.0 to + and the project finally builds. 
In this case, when i try make login with facebook or google, in the console shows the success messages with the returned data but the callback functions in my application are not called.

**Comment by jogboms** [comment]
@raphaelratuczne could you try this out with the latest build?
