### ISSUE TITLE
angular2 support?

### ISSUE THREAD

**Issue by itelo** [mkloubert/nativescript-social-login#2]

**Comment by mkloubert** [comment]
@itelo What so you mean with "Angular" support?

Can you give an example?

**Comment by zoeitsolutions** [comment]
If you could rewrite the code for Typescript and Angular 2.

**Comment by votiakov** [comment]
@itelo @zoeitsolutions You can use it with TypeScript and Angular 2 as it is. What problem do you have?

**Comment by zoeitsolutions** [comment]
@votiakov I have not tried it myself, I was trying to explain what he meant - suggest closing this.
