### ISSUE TITLE
Auto logout of facebook session

### ISSUE THREAD

**Issue by jogboms** [mkloubert/nativescript-social-login#20]
I noticed i had to login everytime i needed to use the Facebook provider, so I delved into the codes and notice you actually called a `logOut` everytime the app initiallizes. 
I don't why you'd do this but i don't quite buy into the idea.

https://github.com/mkloubert/nativescript-social-login/blob/b364e353d0150b0461dbd86a0003741c2d23af0b/plugin/SocialLogin.android.js#L185

https://github.com/mkloubert/nativescript-social-login/blob/b364e353d0150b0461dbd86a0003741c2d23af0b/plugin/SocialLogin.ios.js#L80

**Comment by bradmartin** [comment]
Good thinking the logout for the provider should be a public method the
developer can handle when needed. Would you like to submit a PR with this
functionality?

**Comment by jogboms** [comment]
Yeah @bradmartin. I would do that.

**Comment by jogboms** [comment]
@bradmartin & @mkloubert Tweaks can be found here #21
