### ISSUE TITLE
 Error: The <activity> element must be a direct child of the <application> element [WrongManifestParent]

### ISSUE THREAD

**Issue by kvindasAB** [mkloubert/nativescript-social-login#22]
The build process copies the AndroidManifest.xml inside the project platform and breaks the build. 
As can see in the android manifest provided by the project, the activity is not within an application, also the content of this manifest is exactly the same as the one requested to add in the main AndroidManifest.xml on the documentation.

Full error message is:

```
...platforms/android/src/F8/AndroidManifest.xml:10: Error: The <activity> element must be a direct child of the <application> element [WrongManifestParent]
    <activity android:name="com.facebook.FacebookActivity"
    ^

   Explanation for issues of type "WrongManifestParent":
   The <uses-library> element should be defined as a direct child of the
   <application> tag, not the <manifest> tag or an <activity> tag. Similarly,
   a <uses-sdk> tag must be declared at the root level, and so on. This check
   looks for incorrect declaration locations in the manifest, and complains if
   an element is found in the wrong place.

   http://developer.android.com/guide/topics/manifest/manifest-intro.html

1 errors, 0 warnings
:lintVitalF0F1F2F3F4F5F6F7F8F9F10Release FAILED
```

**Comment by fmsaraujo** [comment]
@kvindasAB, I was having the same issue, but only when bundling with webpack. This was caused by the bundled project having duplicate references to 'com.facebook.FacebookActivity' because I added this activity to my AndroidManifest.xml and it was also present on the plugin's manifest file. Try removing one of the references.
