### ISSUE TITLE
Can we have a newer version of Facebook's SDK?

### ISSUE THREAD

**Issue by jogboms** [mkloubert/nativescript-social-login#23]
I have experienced some issues and conflicts using other facebook-owned libraries. Was wondering if we could update `com.facebook.android:facebook-android-sdk`

**Comment by jogboms** [comment]
@mkloubert I'm working on improving the facebook dependency. I noticed that there wasn't any need for some configurations stated in the README

**Comment by jogboms** [comment]
1. Adding FacebookActivity to the Manifest

**Comment by jogboms** [comment]
2. `app.gradle`
```gradle
buildscript {
    repositories {
        jcenter()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile 'com.google.android.gms:play-services-auth:8.4.0'

    compile('com.twitter.sdk.android:twitter:1.13.2@aar') {
        transitive = true
    }
}
```

Noticed there also wasn't need for this since its been added to the `include.gradle`

**Comment by jogboms** [comment]
```
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>fbauth2</string>
        <string>fbapi</string>
        <string>fb-messenger-api</string>
        <string>fbshareextension</string>
    </array>
```

Can also be moved to an `Info.plist` within the plugin.

**Comment by jogboms** [comment]
So less configuration for the plugin users

**Comment by jogboms** [comment]
@mkloubert are you still available??

**Comment by mkloubert** [comment]
yes

**Comment by jogboms** [comment]
So what do you say to it?

**Comment by mkloubert** [comment]
I will take a look when I am at home again tomorrow.

**Comment by mkloubert** [comment]
Looks great! I think we can merge this branch to the [master](https://github.com/mkloubert/nativescript-social-login).

Before we release, we should set the version number to 2, or better 3 to indicate that we a plugin which runs with NativeScript 3+ and updated SDKs.

**Comment by jogboms** [comment]
@mkloubert ended with a version `3.0.2` after a hard-days work. Also moved the code base to Typescript.

**Comment by mkloubert** [comment]
@jogboms 

Great work! Thank you very much! :-)

**Comment by jogboms** [comment]
You are welcome. I use it too, so i literally had no other choice :);
