### ISSUE TITLE
Issue getting the Google authToken

### ISSUE THREAD

**Issue by pedromareis** [mkloubert/nativescript-social-login#26]
Hello guys, 
I had an issue with the latest version of the plugin (3.0.2) which didn't allow me to get an authToken using the Google Login.
Basically my init data (configurations) for google was being overrided by the default configurations instead of merged.
I've solved it using an older version of the plugin (1.8.1) and using this:
```
    SocialLogin.init({
        activity: void 0,
        google: {
            initialize: true,
            isRequestAuthCode: false,
            serverClientId: "<MY-SERVER-CLIENT-ID>.apps.googleusercontent.com",
            shouldFetchBasicProfile: true,
            scopes: ["profile", "email"]
        }
    });
```

Hope you guys could fix it in the next versions of the plugin, thanks in advance.

**Comment by jogboms** [comment]
@pedromareis thanks for reporting this.
By default, if `isRequestAuthCode` is not passed in the config, it is set to false.
Can you confirm that you added it as a parameter to the config object?

**Comment by pedromareis** [comment]
@jogboms Yes, I've tried that and got the same error. I've also tried to add more parameters like `test: "this is a test"` and while debugging when the plugin merged my configurations with the default ones all the data I've added was gone.

**Comment by jogboms** [comment]
If i may, Could you try running your configurations against the demo app?

On Nov 24, 2017 1:04 PM, "pedromareis" <notifications@github.com> wrote:

@jogboms <https://github.com/jogboms> Yes, I've tried that and got the same
error. I've also tried to add more parameters like test: "this is a test"
and while debugging when the plugin merged my configurations with the
default ones all the data I've added was gone.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mkloubert/nativescript-social-login/issues/26#issuecomment-346814102>,
or mute the thread

**Comment by pedromareis** [comment]
Yeap, same issue...

![screenshot_1511533533](https://user-images.githubusercontent.com/16105597/33214362-8e95b28c-d123-11e7-83a5-3161126f9f44.png)
![screenshot_1511533537](https://user-images.githubusercontent.com/16105597/33214363-8eb6ec36-d123-11e7-9a7d-45f669798ab4.png)

**Comment by pedromareis** [comment]
And using an older version of the plugin (the 1.8.1) it works! 😛 
![screenshot_1511533793](https://user-images.githubusercontent.com/16105597/33214536-473e0f96-d124-11e7-805b-8d1bdca6b501.png)

**Comment by jogboms** [comment]
Thanks @pedromareis. I'm on it now.

**Comment by jogboms** [comment]
@pedromareis could you confirm if installing `@next` solves this issue?

**Comment by pedromareis** [comment]
@jogboms It's working, thank you! 😄

**Comment by jogboms** [comment]
Awesome! Thanks. 👍

**Comment by johnRosalin** [comment]
I am getting a similar error. The authToken is null however, the authCode has data in it.
This is the response that I am getting:
> {
  "provider":"google",
  "code":0,
  "id":"xxxxxxxxxxxxxxxxxxxxx",
  "photo":{},
  "authToken":null,
  "authCode":"4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-aPPFRSBwKMq2rftduwwghfeeKoqzIvAI-IfcRd6NJY",
  "userToken":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "displayName":"xxxxxxxxxxxx",
  "firstName":"xxxx",
  "lastName":"xxxxxxx"
}

I already did the instructions above, also tried reverting to `version 1.8.1` and `@next` but still got a null authToken. Could this be an error on my google app configuration? or am I missing something?

**Comment by jogboms** [comment]
@johnRosalin could you try your current configuration with the demo app, and see what happens?

**Comment by mbd-fondative** [comment]
> @pedromareis could you confirm if installing `@next` solves this issue?

how to install @next and why ?? 
thank you ..

**Comment by mbd-fondative** [comment]
> @jogboms It's working, thank you!

how to install @next please 
thank you...

**Comment by jogboms** [comment]
@Marwen238 Soory for the delay, @next is the latest version, no need installing @next. Use the latest version.
