### ISSUE TITLE
Login causes trouble on opening other activities like Camera

### ISSUE THREAD

**Issue by pedromareis** [mkloubert/nativescript-social-login#27]
Hello again,
I think I've found another bug on the plugin (the latest version 3.0.3). Basically after I login with both fb and google, every time I try to open the Camera (to use the barcode-scanner plugin) or the Gallery (using the image-picker plugin) it has a strange behaviour, when I get a response from those plugins (ex: when I get the image I select with the plugin) it assumes the callback from the SocialLogin.login...(...).

**Comment by jogboms** [comment]
If I get you correctly, the callback you attached to the social-login is being called whenever a result is returned from these plugins? @pedromareis

**Comment by jogboms** [comment]
@pedromareis could you confirm if the `@next` build solves this issue for you?

**Comment by pedromareis** [comment]
@jogboms About the first question you've asked, the answer is yes, the callback of the social-login is being called whenever I use the other plugins. 
Relative to the second one, I've tried it (nativescript-social-login@3.0.5-24-11-17.6-12) and the issue is still there.

**Comment by jogboms** [comment]
Okay @pedromareis. I'm still on it.

**Comment by jogboms** [comment]
@pedromareis i just push a fix to `@next` again

**Comment by pedromareis** [comment]
@jogboms still not working 😭

**Comment by jogboms** [comment]
That's strange... could you clear your platforms?

**Comment by pedromareis** [comment]
@jogboms Okay, it's working!! Thank you so much, you rock! 😄😄😄
