### ISSUE TITLE
IOS Google Login no response

### ISSUE THREAD

**Issue by Willis0826** [mkloubert/nativescript-social-login#29]
Dear teams,

I am a newbie in NativeScript, I follow the instruction to set up my Application.
**The google and facebook login works prefect in Android**, It's will open the correct page to handle the login process, and once the process be done I will get the user result from callback !
However, when I jump into **IOS, the google login is out of function**, after I called `SocialLogin.loginWithGoogle` will crash the application, I tried both iPhone & simulator.

**Here is my testing result :** 

IOS : 10.2.1、11.2
nativescript-social-login: "^3.0.5"
tns-platform-declarations: "^3.3.0"
tns-core-modules: "~3.1.1"

Due to there is no error message been log, I couldn't figure out where I did wrong.
Any suggestion would be helpful !

**Comment by jogboms** [comment]
Thanks for reporting this issue. Could i suggest you try out the demo application included? It shows how this plugin can be implemented on both iOS and Android.

**Comment by Willis0826** [comment]
@jogboms Thank you for suggestion, I will try the demo tomorrow, hope I can solve the problem which I faced.

**Comment by Willis0826** [comment]
@jogboms I had tried the demo this morning. Unfortunately, **the demo running on IOS failed to process google login**, but the facebook login works perfectly.

Here is my testing  result : 
IOS : 10.2.1、11.2
nativescript-social-login: "^3.0.5"
tns-platform-declarations: "^3.3.0"
tns-core-modules: "3.2.0"

The console didn't log any error message, once I clicked the "Login with Google", the application was crash.

**Comment by jogboms** [comment]
Okay @Willis0826. I'd check it out.

**Comment by jogboms** [comment]
@Willis0826 could you try installing the `@next` version and confirm if its working for you?

**Comment by Willis0826** [comment]
@jogboms Spectacular! After I used `npm install --save nativescript-social-login@next` everything works perfectly!

**Now, the plugin can running  on my iPhone(10.2.1)** without any error! Thank you for great help.

**Comment by jogboms** [comment]
Awesome. Thanks for your feedbacks @Willis0826

**Comment by Willis0826** [comment]
Recently, Our team used this package to implement the login function in our Application.
And we found a problem is : **The function `invokeLoginCallbackForGoogle` which is in the `SocialLogin.ios.js` didn't pass the photo property**, I am not sure if this is a bug or not. 

However, we using the `user.profile.imageURLWithDimension(100)` to get the user photo url, and then pass it to `googleSuccessCallback` function.

@jogboms Here to share, hope this will help.

**Comment by NikicaAsanin** [comment]
Problem with GoogleLogin on iOS , android works perfectly. On button click I get log login with google..
and then nothing happen, no google login popup. help?
