### ISSUE TITLE
login function can only called once in Android

### ISSUE THREAD

**Issue by nicHoch** [mkloubert/nativescript-social-login#30]
Using the login functions (loginWithGoogle/FB) is working fine. But i can only call it once.
Not the same login provider or any other again.

  "tns-android": {
      "version": "3.3.1"
    }

 "nativescript-social-login": "^3.0.6",

Then I got following error:

(loginWithGoogle()): Starting activity for result...
JS: [nativescript-social-login]: (loginWithGoogle()): [ERROR] runOnUiThread(): Error: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
JS:     android.support.v4.app.BaseFragmentActivityApi14.checkForValidRequestCode(BaseFragmentActivityApi14.java:79)
JS:     android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:705)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.app.Activity.runOnUiThread(Activity.java:4713)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.onClick(Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.java:12)
JS:     android.view.View.performClick(View.java:4438)
JS:     android.view.View$PerformClick.run(View.java:18422)
JS:     android.os.Handler.handleCallback(Handler.java:733)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:136)
JS:     android.app.ActivityThread.main(ActivityThread.java:5001)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
JS:     dalvik.system.NativeStart.main(Native Method)

**Comment by jogboms** [comment]
@nicHoch Thanks for reporting this error. 
Can you please confirm if this is also reproducible in the demo app?

**Comment by nicHoch** [comment]
i did not get any error message in the demo but after login with google i can not login with FB unless i init again.
is that by intention?

**Comment by jogboms** [comment]
Are you using the Plain Nativescript or w/ Angular?

**Comment by raman-nbg** [comment]
I have the same issue here. Using zone did not help.
This issue also occurs when the user closes the Facebook login screen with tapping on the "x". After that the login screen can not be opened again. But I can't see any errors like @nicHoch.

**Comment by jogboms** [comment]
@raman-nbg could you try this fix for android?

``` ts
import { init } from "nativescript-social-login";
import { android as Android, AndroidApplication } from "application";

// Initialize Social Login
Android.on(AndroidApplication.activityResumedEvent, () => {
    // Fixes bug that causes it not to use activity more than once
    init({
        facebook: { clearSession: false }
    });
});
```

**Comment by raman-nbg** [comment]
@jogboms  that worked! Thanks! 👍 

Can you explain why I have to invoke init again? I already initialized SocialLogin on the activityCreatedEvent. What happens here?

```JavaScript
import Application = require("application");
import SocialLogin = require("nativescript-social-login");
import { IInitializationResult } from "nativescript-social-login";

Application.android.on(Application.AndroidApplication.activityCreatedEvent, (event) => {
    const result: IInitializationResult = SocialLogin.init({
        activity: event.activity,
        facebook: {
            initialize: true,
            clearSession: false
        },
        google: {
            initialize: false
        }
    });

    if (result.facebook.error || !result.facebook.isInitialized) {
        console.log("Could not initialize facebook login");
        console.error(result.facebook.error);
    }
});
```


Is there any difference in `SocialLogin.init()` with importing `import SocialLogin = required("nativescript-social-login");` and `init()` with importing from `import { init } from "nativescript-social-login";`?

**Comment by jogboms** [comment]
@raman-nbg The difference is in the events `activityCreatedEvent` and `activityResumedEvent`. The former only being called once but since a new activity is initialized ie facebook, the `init` function is never called again since, at that point, the foreground Activity is only suspended and then resumed.
