### ISSUE TITLE
absolut path in demo: package.json

### ISSUE THREAD

**Issue by nicHoch** [mkloubert/nativescript-social-login#31]
should be changed to:

```
 "dependencies": {
    "nativescript-social-login": "file://../plugin/",
```

**Comment by jogboms** [comment]
@nicHoch Thanks for reporting this.
Borrowing from the official plugin seed, the demo app should be initiated using the npm scripts within `plugin` directory e.g `demo.android` or `demo.ios`.

**Comment by jdmcnair** [comment]
OK, so it looks like I just needed to change that to point to the `/src` directory.

**Comment by jogboms** [comment]
oh @jdmcnair. Yeah you could do that, but its most preferred to run the demo from within the `src` folder using `npm run demo.android` or `npm run demo.ios` for the first time. This way, you don't have to bother about paths.
