### ISSUE TITLE
duplicate entry: com/google/zxing/BarcodeFormat.class

### ISSUE THREAD

**Issue by arielnmz** [mkloubert/nativescript-social-login#32]
This plugin collides directly with [nativescript-barcode-scanner](https://github.com/EddyVerbruggen/nativescript-barcodescanner) because of its dependency on `com.google.zxing`, which means you can't have both installed at the same time, otherwise the build fails with the following error: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForF0F1F2F3F4F5F6F7F8F9Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/BarcodeFormat;
```

Now, enabling multidex won't work as it will just fail because of duplicate classes:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForF0F1F2F3F4F5F6F7F8F9Debug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/BarcodeFormat.class
```

The solution is to just exclude the `com.google.zxing` group when compiling `com.facebook.android:facebook-android-sdk` by replacing this line:

`compile "com.facebook.android:facebook-android-sdk:$facebookSDKVersion"`

With this one:

`compile ("com.facebook.android:facebook-android-sdk:$facebookSDKVersion"){ exclude group: 'com.google.zxing' }`

In the `include.gradle` file.

**Comment by jogboms** [comment]
Thanks @arielnmz 🌮 

I'd run a test on this and apply the fix to the npm release.

**Comment by jogboms** [comment]
@arielnmz I review the issue and realized facebook added the dependency with the latest release. 

You could try one of two things within your `app.gradle`. 

Update your dependencies
```
dependencies {
    compile ("com.facebook.android:facebook-android-sdk:[4,5)"){
        exclude group: 'com.google.zxing'
    }
}
```

Or force facebook to a particular version
```
android {
    project.ext {
        facebookSDKVersion = "4.25.0"
    }
}
```

**Comment by arielnmz** [comment]
Regarding the first solution, the build process is apparently ignoring the `compile(...) { exclude group ... }` statement on `app.gradle`, as it has no effect on the build (the duplicated class error still shows up), moving it to inside the `android` block doesn't work either. The second solution, manually specifying a Facebook SDK version, works though.

And for reference, [starting from version 4.26](https://developers.facebook.com/docs/android/change-log-4x#4_26_0) of the Facebook SDK you can scan QR codes, so any version below that will not include the `com.google.zxing` group. If you still need to use any version higher than 4.25 you will need to manually add the `exclude group` statement directly to the plugin's `include.gradle` file.
