### ISSUE TITLE
Tns run not runnig. 

### ISSUE THREAD

**Issue by govi2010** [mkloubert/nativescript-social-login#34]
![image](https://user-images.githubusercontent.com/8776031/34647650-b7d72642-f3ad-11e7-935d-0c27b0f65c62.png)

**Comment by jogboms** [comment]
@govi2010 can you add more info to it.

**Comment by saiprasath-swaas** [comment]
The same error iam getting, **Cannot find namespace 'android'. in SocialLogin-common.d.ts file**.
I have following configuration in my project:
tns: ^3.4.2
nativescript-social-login: ^3.0.5
npm: ^5.6.0

I have installed android platform via **tns platform add android**
Clarify Thanks.
