### ISSUE TITLE
IOS Facebook Login Problem

### ISSUE THREAD

**Issue by NikicaAsanin** [mkloubert/nativescript-social-login#39]
I have problem with IOS login with Facebook. Android works normally but IOS is not.
I get this error on call function:
**CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'Login.loginWithProvider')
CONSOLE ERROR [native code]: ERROR CONTEXT [object Object]**

I am using your example and also in main.ts or app.ts file  **const errorRef = new interop.Reference();** showing error on this line for interop - [ts] Cannot find name 'interop'.

**Comment by derekkite** [comment]
Look in the demo app. 
https://github.com/mkloubert/nativescript-social-login/blob/master/demo/package.json#L18
and 
https://github.com/mkloubert/nativescript-social-login/blob/master/demo/references.d.ts
copy the references.d.ts and install the linked module using npm.

**Comment by NikicaAsanin** [comment]
@derekkite Thanks for replay, but I pass threw all demo app files and configuration and nothing still on FB login - **CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'Login.loginWithProvider')**

**Comment by NikicaAsanin** [comment]
Here is my code below.

**Main.ts**
`import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app.module";

import * as application from "application";
import * as platform from "platform";
import * as utils from "utils/utils";
import Application = require("application");
import SocialLogin = require("nativescript-social-login");
declare var android: any;
// declare var UIResponder: any;
// declare var UIStatusBarStyle: any;
// declare var UIApplication: any;
// declare var UIApplicationDelegate: any;
declare class UIResponder {};
declare class UIApplicationDelegate{};
declare class FBSDKApplicationDelegate {
  static sharedInstance():any;
};

declare class GGLContext {
  static sharedInstance():any;
};

declare class GIDSignIn {
  static sharedInstance():any;
};

declare class FBSDKAppEvents{
  static activateApp();
};
declare class UIApplication {};
declare class NSDictionary {};

if (Application.android) {
  Application.android.on(Application.AndroidApplication.activityResumedEvent, () => {
      let result = SocialLogin.init();
  });
}
if (application.ios) {

  class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary): boolean {
      let gglDelegate = false;

      try {
        const errorRef = new interop.Reference();
        GGLContext.sharedInstance().configureWithError(errorRef);

        const signIn = GIDSignIn.sharedInstance();
        gglDelegate = true;
      } catch (error) {
        console.log(error);
      }

      const fcbDelegate = FBSDKApplicationDelegate.sharedInstance().applicationDidFinishLaunchingWithOptions(application, launchOptions); // facebook login delegate

      return gglDelegate || fcbDelegate;
    }

    applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {
      const fcbDelegate = FBSDKApplicationDelegate.sharedInstance().applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation); // facebook login delegate
      const gglDelegate = GIDSignIn.sharedInstance().handleURLSourceApplicationAnnotation(url, sourceApplication, annotation); // google login delegate

      return fcbDelegate || gglDelegate;
    }
  }

  application.ios.delegate = MyDelegate;
}

    
platformNativeScriptDynamic().bootstrapModule(AppModule);
`
**loginRegister.ts**
`import { Component, ElementRef, OnInit, ViewChild, NgZone } from "@angular/core";
import { Observable } from 'data/observable';
import { Page, ShownModallyData, NavigatedData } from "tns-core-modules/ui/page";
import { Http, Headers, Response, HttpModule } from "@angular/http";
import "rxjs/add/operator/do";
import "rxjs/add/operator/map";
import "rxjs/add/observable/throw";
import { ActivatedRoute, Router, NavigationStart } from "@angular/router";
import "rxjs/add/operator/catch";
import { UserLogin } from "../../model/userLogin";
import { UserProfile } from "../../model/userProfile";
import { UserService } from "../../service/userService";
import * as ApplicationSettings from "application-settings";
import * as dialogs from "ui/dialogs";
import * as frame from "ui/frame";
import SocialLogin = require("nativescript-social-login");


@Component({
    moduleId: module.id,
    selector: "loginRegister",
    templateUrl: "loginRegister.component.html",
    styleUrls: ["loginRegister.component.css"]
})
export class LoginComponent implements OnInit {
   
    user: UserLogin;
    userRegister: UserProfile;
    currentUser;
    showRegister = false;
    showLogin = true;
    socialButtons = true;
    showPasswordReset = false;


    constructor(public _userService: UserService, public _router: Router, private _ngZone:NgZone) {

        let viewModel = new Observable();

    }

    public checkUser() {
        if (ApplicationSettings.hasKey("user")) {
            this.currentUser = JSON.parse(ApplicationSettings.getString("user"));
        } else {
            this.currentUser = undefined;
        }
        if (this.currentUser != undefined) {
            this._router.navigate(["/home"]);
        } else {
            this._router.navigate(["/loginRegister"]);
        }
        console.log("currentUser: " + JSON.stringify(this.currentUser));
    }

    public onSignIn() {



        this._userService.userLogin(this.user).subscribe(
            data => {

                console.log("logovan" + JSON.stringify(data));
                ApplicationSettings.setString("user", JSON.stringify(data));
                this._router.navigate(["/home"]);

            },
            error => {
                console.log("nije logovan" + error);
                this.onFalseSignIn();
            }
        );

    }

    public onSignUp() {
        this._userService.userRegister(this.userRegister).subscribe(
            data => {
                console.log("registrovan" + JSON.stringify(data));
                this.onRegisterSuccess();
            },
            error => {
                console.log("nije registrovan" + error);
            }
        );
    }


    public onFacebookSignIn() {
     
        // SocialLogin.loginWithFacebook((result) => {
        //     if (result.authToken) {
        //         console.log(result.authToken);
        //     }
        // });      
         SocialLogin.loginWithFacebook((result) => {
            this._ngZone.run(() => {
                console.log("code: " + result.code);
                console.log("error: " + result.error);
                console.log("userToken: " + result.userToken);
                console.log("displayName: " + result.displayName);
                console.log("photo: " + result.photo);
                console.log("authToken: " + result.authToken);
            });
        });
      
    }

   

    public goToPasswordReset() {
        this.showLogin = false;
        this.showPasswordReset = true;
        this.socialButtons = false;
    }
    public goToSignIn() {
        this.showRegister = false;
        this.showLogin = true;
        this.showPasswordReset = false;
        this.socialButtons = true;
    }
    public goToRegister() {
        this.showRegister = true;
        this.showLogin = false;
        this.socialButtons = true;
    }
    ngOnInit() {
        this.user = new UserLogin;
        this.userRegister = new UserProfile;
        this.checkUser();
     
     
    }

    public onRegisterSuccess() {
        dialogs.alert({
            title: "Success",
            message: "Your acccount is created.",
            okButtonText: "Go and Sign in"
        }).then(() => {
            console.log("Dialog closed!");
            this.goToSignIn();

        });
    }

    public onFalseSignIn() {
        dialogs.alert({
            title: "Ops!",
            message: "Something went wrong.\nEmail or Password is incorrect.",
            okButtonText: "Close"
        }).then(() => {
            console.log("Dialog closed!");


        });
    }
}`

**Packet.json**

`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.strawberrymobileapp",
    "tns-ios": {
      "version": "3.4.1"
    },
    "tns-android": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-cardview": "^2.0.5",
    "nativescript-gradient": "^2.0.1",
    "nativescript-ngx-fonticon": "^4.0.0",
    "nativescript-social-login": "^3.0.8",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "^3.4.1",
    "tns-platform-declarations": "^3.4.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }
}
`

**tnsConfig.json**
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2016"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "lib",
        "hooks",
        "node_modules",
        "platforms"
    ]
}`

**Comment by NikicaAsanin** [comment]
And Android works perfect with Facebook and this code above.

**Comment by NikicaAsanin** [comment]
Solve problem , I didn't see that I have only call SocialLogin init or android so I did it for IOS too and it works now.
`ngOnInit() {
    if (Application.android) {
      Application.android.on(Application.AndroidApplication.activityResumedEvent, () => {
        let result = SocialLogin.init();
      });
    } else if (Application.ios) {
      let result = SocialLogin.init();
    }

  }`

**Comment by SalehMahmood** [comment]
No luck to me, anybody knows any solution?
