### ISSUE TITLE
Readme installation instructions issue

### ISSUE THREAD

**Issue by chriso86** [mkloubert/nativescript-social-login#44]
Hi,

I've started installing this plugin using the installation notes at:
https://nativescript-sociallogin.readme.io/

Issue:

First, a syntax error:

```
if (Application.android) {
    Application.android.onActivityCreated = (activity) => {
        var result = SocialLogin.init({
            activity: activity
        });
    });
}
```

Second, onActivityCreated does not exist on type AndroidApplication.
Does this not work out of the box with TypeScript? It's tagged as a TypeScript project on GitHub...

I think it may need to be something like:
```
if (Application.android) {
    Application.android.on('activityCreated', (activity) => {
        var result = SocialLogin.init({
            activity: activity
        });
    });
}
```

I have tried looking around for a solution, and I'm still looking around.
Just thought I would bring this to your attention, hope I'm not wasting your time.

Cheers,
Chris

**Comment by jogboms** [comment]
Thanks @chriso86, corrections would be made to the README. 👍
