### ISSUE TITLE
Failed to build with tns-android 4.0.0

### ISSUE THREAD

**Issue by exeleon** [mkloubert/nativescript-social-login#45]
I have:
nativescript-social-login: 3.0.11
nativescript-cli: 4.0.0
tns-android: 4.0.0

Trying to build with tns-android version 4.0.0 fails with this:

Failed to build plugin nativescript-social-login :
Error: Command failed: ./gradlew -p /home/mlopera/AA/mobile.ns/platforms/tempPlugin/nativescript_social_login assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mlopera/AA/mobile.ns/platforms/tempPlugin/nativescript_social_login/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating root project 'nativescript_social_login'.
> Could not find method classpath() for arguments [com.android.tools.build:gradle:3.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Maybe related to [this introduced change](https://github.com/NativeScript/android-runtime/issues/938)

**Comment by jogboms** [comment]
@exeleon Thanks for pointing this out.
What version of `tns-android` are you currently running on?

**Comment by jogboms** [comment]
Haven't worked out support for `4.0.0` yet. Would see a way to test it out myself. 
Just watch this space for any developments.

**Comment by exeleon** [comment]
@jogboms I think the issue is around the gradle plugin updated in ns 4.0.0. Thank you in advance for your support!

**Comment by exeleon** [comment]
The android official doc provides info about some [known issues](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#known_issues). I suspect this is the cause: 

> Loading the Android plugin multiple times in a single build leads to a project sync error. This can occur when you have multiple subprojects that each include the Android plugin in their buildscript classpath.

**Comment by juliancesar** [comment]
I have the same issue.

**Comment by jogboms** [comment]
@NikicaAsanin @juliancesar could you try the solution proposed by @exeleon and see if it works for you so as to publish a hot fix?

**Comment by ssajith** [comment]
@jogboms Solution proposed by @exeleon works for me
I have naticescript-cli@4.0.1, tns-android@4.0.1, nativescript-social-login@4.0.0

**Comment by jogboms** [comment]
@NikicaAsanin @juliancesar @exeleon @ssajith a new version has been published with a fix for this issue.

@ssajith could you please open a new issue so we can track that from there?

**Comment by next-apps** [comment]
@jogboms Done. Opened issue #50
