### ISSUE TITLE
Failed to build after upgrading to tns@4.0.0

### ISSUE THREAD

**Issue by anaszgh** [mkloubert/nativescript-social-login#47]
I have upgraded the project to tns version 4.0.0, after that the tns run android command stopped working with the following error

```
Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-social-login :
Error: Command failed: gradlew.bat -p .\platforms\tempPlugin\nativescript_social_login assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1

FAILURE: Build failed with an exception.

* Where:
Build file '.\tempPlugin\nativescript_social_login\build.gradle' line: 59

* What went wrong:
A problem occurred evaluating root project 'nativescript_social_login'.
> Could not find method classpath() for arguments [com.android.tools.build:gradle:2.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**Comment by jogboms** [comment]
Hello @anaszgh.
What version of `nativescript-social-login` are you running on?
Use the latest version.

**Comment by jorgerb79** [comment]
I have the same issue. 

I have created a new project using tns-cli 4.0.0, and added the lastest version of the plugin. The error message is exactly the same.

**Comment by jogboms** [comment]
@anaszgh did you follow the new instructions in the README?

**Comment by nicHoch** [comment]
I have the same issue: 

Plugin: nativescript-social-login@4.0.0
OS: Android tns-android : 4.0.1
"tns-core-modules": "^4.0.0"

**Comment by jogboms** [comment]
@nicHoch can you also confirm if you followed the new instructions on the README?

**Comment by jorgerb79** [comment]
I followed the README file. Also I upgraded a working project from version 3.0.8 (tns-core-modules 3.4.1) to 4.0.0 (tns-core-modules: 4.0.0) and it stopped to compile displaying the same error.

**Comment by jogboms** [comment]
@jorgerb79 i really don't see why it shouldn't. How about the demo app?

**Comment by fumpierrez** [comment]
I'm having the exact same issue (same error output), unfortunately I can't provide much details as I'm completely new to nativescript (installed it today so on latest versions of everything). I followed the readme and added the config to graddle. I'm using the vuejs template but ran npm run clean like for other plugins, if that matters. I'll run the demo when I find out how


> Unable to apply changes on device: emulator-5554. Error is: Failed to build plugin nativescript-social-login :
> Error: Command failed: ./gradlew -p /data/frontendns/dist/platforms/tempPlugin/nativescript_social_login assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/data/frontendns/dist/platforms/tempPlugin/nativescript_social_login/build.gradle' line: 59
> 
> * What went wrong:
> A problem occurred evaluating root project 'nativescript_social_login'.
> > Could not find method classpath() for arguments [com.android.tools.build:gradle:2.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by jorgerb79** [comment]
@jogboms, I tried running the demo, and the error is exactly the same. Does the demo require changes to run properly?

**Comment by anaszgh** [comment]
@jogboms Yes, i have tried to follow the new instructions, and also used the latest version of the plugin, but the error is still the same.

**Comment by jogboms** [comment]
@anaszgh @fumpierrez @nicHoch could you see here? #49
