### ISSUE TITLE
Nativescript tns@4.0.0 Android Error on build 

### ISSUE THREAD

**Issue by NikicaAsanin** [mkloubert/nativescript-social-login#49]
**Still getting error above, I have everything up to date and I get this error on android -**

`Unable to apply changes on device: 520069a6f47cc4b3. Error is: Failed to build plugin nativescript-social-login :
Error: Command failed: ./gradlew -p /Users/nikicaasanin/Documents/Strawberry/strawberry-mobile-app/platforms/tempPlugin/nativescript_social_login assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.1 -PsupportVersion=26.0.0-alpha1

FAILURE: Build failed with an exception.

Where:
Build file '/Users/nikicaasanin/Documents/Strawberry/strawberry-mobile-app/platforms/tempPlugin/nativescript_social_login/build.gradle' line: 59

What went wrong:
A problem occurred evaluating root project 'nativescript_social_login'.

Could not find method classpath() for arguments [com.android.tools.build:gradle:2.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org`

**Comment by jorgerb79** [comment]
I've found that removing:

```
dependencies {
    classpath 'com.android.tools.build:gradle:2.1.0'
    classpath 'com.google.gms:google-services:3.0.0'
} 
```

from include.gradle in the plugin, fixes the issue in my enironment. I hope this can give a clue to fix this issue.

**Comment by jogboms** [comment]
@NikicaAsanin could you try what @jorgerb79 suggested?

**Comment by jogboms** [comment]
#47

**Comment by NikicaAsanin** [comment]
@jogboms I sume this might fix the problem but every time I install node_modules it's going to rewrite the include.gradle

**Comment by jogboms** [comment]
Yeah @NikicaAsanin. I know this but let continue this discussion on the open thread #47
