### ISSUE TITLE
Request for IOS

### ISSUE THREAD

**Issue by chanmyaethu-mn** [mkloubert/nativescript-social-login#5]
Hi mkloubert,
Do you have any idea for ios?
I really would like to use your plugin in ios.
Thank
Chan Myae Thu

**Comment by zoeitsolutions** [comment]
+ 1

**Comment by votiakov** [comment]
Hello!

I want to write the ios part for Google and Facebook login. Then we could add Twitter login together.

@mkloubert please let me know if you already started implementing ios functionality.

**Comment by zoeitsolutions** [comment]
@votiakov this would be great. I definitely think a lot of nativescript devs are wanting to use a single social plugin for both platforms.

I will gladly test from my side and provide feedback.

**Comment by votiakov** [comment]
Hello!

I have good news - facebook login now works on ios.


![screen shot 2017-01-13 at 23 13 06](https://cloud.githubusercontent.com/assets/6445101/21947660/87468efa-d9e6-11e6-8433-7b083a84a797.png)
![screen shot 2017-01-13 at 23 12 53](https://cloud.githubusercontent.com/assets/6445101/21947659/873a33da-d9e6-11e6-8bee-cb2a9d8d1818.png)

I will continue with google tomorrow or on Sunday.

@mkloubert please get in touch with me, I want to discuss some features.

Cheers!

**Comment by mkloubert** [comment]
@votiakov Great! :-)

Of course, lets starts discussing...

**Comment by votiakov** [comment]
Oh hey! 

Most of all I am interested in making this easy to configure and use for developers. I personally spent 2 full days implementing facebook and google login for my app - for both platforms, and this was a nightmare ) 

Basically there is a problem with tns platform declarations on ios - described in this [issue](https://github.com/NativeScript/NativeScript/issues/2724).

Using facebook login requires adding platform declarations to references file and plus adding some manual declarations - which is a workaround for this bug.

For example if you want to use this with nativescript application - you should add this to the references file:

`declare type FormData = any;`
`declare var FormData;`
`declare type Blob = any;`
`declare var Blob;`

But if you want to use it with nativescript-angular application, you will have to add this:


`declare type Comment = any;`
`declare type CloseEvent = any;`
`declare type Document = any;`
`declare type DocumentFragment = any;`
`declare type Element = any;`
`declare type History = any;`
`declare type HTMLAnchorElement = any;`
`declare type HTMLCollection = any;`
`declare type HTMLDocument = any;`
`declare type HTMLElement = any;`
`declare type HTMLInputElement = any;`
`declare type HTMLScriptElement = any;`
`declare type HTMLStyleElement = any;`
`declare type KeyboardEvent = any;`
`declare type Location = any;`
`declare type MessageEvent = any;`
`declare type MouseEvent = any;`
`declare type Node = any;`
`declare type NodeList = any;`
`declare type Text = any;`
`declare type WebSocket = any;`



And this is not over.. You will have to also add 10-15 more declarations to write delegate for ios. 

And finally my question. Should I leave it as it is and just give a link to the issue with the explanations what to do, or should I take responsibility and provide reference files for usual app and for angular app?

**Comment by mkloubert** [comment]
@votiakov You should first finish implementation and simply add the link to the issue.

But I don't think, that it is currently nessessary to add the declaration files, because the platform specific files of the module are written in plain JavaScript, what makes it in my opinion much easier to develop.

The only needed (and for developers interesting) TypeScript stuff is defined in the [index.ts](https://github.com/votiakov/nativescript-social-login/blob/andrii_dev/plugin/index.ts).

**Comment by zoeitsolutions** [comment]
@votiakov how far are you with the implementation for iOS?

**Comment by votiakov** [comment]
Hi @zoeitsolutions !

Thanks for reminding me. It is close to finish. Then it will need some refactor. 
I will sit down and finish it tomorrow night.

**Comment by zoeitsolutions** [comment]
Hi @votiakov ,

Thank you very much for your efforts so far, good luck!

**Comment by mkloubert** [comment]
@votiakov 

Very good news! :-)

Please only do the changes in the [andrii_dev branch](https://github.com/votiakov/nativescript-social-login/tree/andrii_dev) and make a pull request to my repository and I do the work with the merging and the releasing to the official [npm package](https://www.npmjs.com/package/nativescript-social-login).

Have you got an account at [npmjs.com](https://www.npmjs.com/)? So I can add you as "collaborator" there.

**Comment by votiakov** [comment]
Hello folks!

I just finished with ios support for today.
Both facebook and google now work, but I still have to fight with google response codes.
You can try it from my [branch](https://github.com/votiakov/nativescript-social-login/tree/andrii_dev), I will refactor this mess and update readme later. I need to sleep now ;) 

Yes @mkloubert, my npm profile is https://www.npmjs.com/~votiakov

**Comment by mkloubert** [comment]
@votiakov 

What I forgot to ask: Do you have an account on Twitter?

**Comment by votiakov** [comment]
Not yet, but I could create one if needed

**Comment by mkloubert** [comment]
@votiakov 

This is only for the thing after I released the new version.

I will create a new tweet for that, so [NativeScript](https://twitter.com/NativeScript) and other developers get noticed.

So I would link to your Twitter account, so anyone will know that you did the great work ;-)

**Comment by votiakov** [comment]
Oh that's great thanks )
I have to update the readme for google now. Unfortunately there is a lot of configuration on iOS. 
Could you please checkout my branch and test things out? This question is for everyone who reads this thread!

**Comment by mkloubert** [comment]
@votiakov 

Of course! ;-)

**Comment by votiakov** [comment]
It is ready for a PR. Hopefully I did not forget anything

**Comment by mkloubert** [comment]
**Version 1.5.0 is now officially released!**
