### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by gowthamcodingmart** [mkloubert/nativescript-social-login#9]
Can you please provide an example for using this plugin in Nativescript+Angular 2. I don't know how to implement the code in Angular 2. It always showing me errors.

**Comment by votiakov** [comment]
Hello @gowthamcodingmart !

 I use this plugin with angular. What problems do you have?

**Comment by gowthamcodingmart** [comment]
This plug-in is not working fine for me. `const errorRef = new interop.Reference();` This always gives error to me. How can i solve this error. Can u please provide a demo code.

**Comment by gowthamcodingmart** [comment]
Please provide a working code for Social Login using G+. It would be very helpful.
Thanks in advance.
